apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-monolith
  namespace: petclinic-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-monolith
  template:
    metadata:
      labels:
        app: petclinic-monolith
    spec:
      containers:
        - name: petclinic-monolith
          image: petclinic-monolith
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "h2"
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-monolith
  namespace: petclinic-monolith
spec:
  selector:
    app: petclinic-monolith
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
