apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: springcommunity/spring-petclinic-vets-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: petclinic-microservices
spec:
  selector:
    app: vets-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
