@startuml
'https://plantuml.com/component-diagram
top to bottom direction

package "PetClinic Module" {

  package "Infrastructure" {
     [Controller]
     [Repository]
     [Module Management]
  }

  package "Domain" {
     [Aggregates]
     [Value Objects]
  }

  [Controller] ..> [Repository]
  "Infrastructure" ..> "Domain"
  [Controller] ..> [Module Management]
}

@enduml
