@startuml
'https://plantuml.com/component-diagram
left to right direction


package "PetClinic Application" {

package "UI Layer (View)" {
     [User Interface]
}

package "Owner Module" {

  package "Application Logic Layer (Owner)" {
     OwnerControllerAPI--[OwnerController]
     [OwnerManagement]
  }

  package "Business Logic Layer (Owner)" {
     OwnerModelAPI--[Domain Owner]
     OwnerRepoAPI--[OwnerRepository]
  }

  [OwnerController] --( OwnerModelAPI
  [OwnerController] --( OwnerRepoAPI
  [OwnerRepository] -( OwnerModelAPI
  [OwnerManagement] --( OwnerModelAPI
  [OwnerManagement] --( OwnerRepoAPI
}

package "Pet Module" {

  package "Application Logic Layer (Pet)" {
     PetControllerAPI--[PetController]
     [PetManagement]
  }

  package "Business Logic Layer (Pet)" {
     PetModelAPI--[Domain Pet]
     PetRepoAPI--[PetRepository]
  }

  [PetController] --( PetModelAPI
  [PetController] --( PetRepoAPI
  [PetManagement] --( PetModelAPI
  [PetManagement] --( PetRepoAPI
  [PetRepository] -( PetModelAPI
}

package "Visit Module" {

  package "Application Logic Layer (Visit)" {
     VisitControllerAPI--[VisitController]
     [VisitManagement]
  }

  package "Business Logic Layer (Visit)" {
     VisitModelAPI--[Domain Visit]
     VisitRepoAPI--[VisitRepository]
  }

  [VisitController] --( VisitModelAPI
  [VisitController] --( VisitRepoAPI
  [VisitManagement] --( VisitModelAPI
  [VisitManagement] --( VisitRepoAPI
  [VisitRepository] -( VisitModelAPI
}

[User Interface] --( OwnerControllerAPI
[User Interface] --( PetControllerAPI
[User Interface] --( VisitControllerAPI



[PetManagement] -[hidden]d- [OwnerController]
[VisitManagement] -[hidden]d- [OwnerController]


}
@enduml