@startuml
'https://plantuml.com/component-diagram
left to right direction


package "PetClinic Application" {

package "UI Layer (View)" {
     [User Interface]
}

package "Owner Module" {

  package "Application Logic Layer (Owner)" {
     [OwnerController]
     OwnerManagementAPI--[OwnerManagement]
     [OwnerController] -( OwnerManagementAPI
  }

  package "Business Logic Layer (Owner)" {
     [Domain Owner]
     [OwnerRepository]
  }

  OwnerModelAPI--[Domain Owner]
  OwnerRepoAPI--[OwnerRepository]
  [OwnerController] --( OwnerModelAPI
  [OwnerController] --( OwnerRepoAPI
  [OwnerRepository] -( OwnerModelAPI
  [OwnerManagement] --( OwnerModelAPI
  [OwnerManagement] --( OwnerRepoAPI
}
OwnerControllerAPI--[OwnerController]

package "Pet Module" {

  package "Application Logic Layer (Pet)" {
     [PetController]
     PetManagementAPI--[PetManagement]
     [PetController] -( PetManagementAPI
  }

  package "Business Logic Layer (Pet)" {
     [Domain Pet]
     [PetRepository]
  }

  PetModelAPI--[Domain Pet]
  PetRepoAPI--[PetRepository]
  [PetController] --( PetModelAPI
  [PetController] --( PetRepoAPI
  [PetManagement] --( PetModelAPI
  [PetManagement] --( PetRepoAPI
  [PetRepository] -( PetModelAPI
}
PetControllerAPI--[PetController]

package "Visit Module" {

  package "Application Logic Layer (Visit)" {
     [VisitController]
     VisitManagementAPI--[VisitManagement]
     [VisitController] -( VisitManagementAPI
  }

  package "Business Logic Layer (Visit)" {
     [Domain Visit]
     [VisitRepository]
  }
  VisitModelAPI--[Domain Visit]
  VisitRepoAPI--[VisitRepository]
  [VisitController] --( VisitModelAPI
  [VisitController] --( VisitRepoAPI
  [VisitManagement] --( VisitModelAPI
  [VisitManagement] --( VisitRepoAPI
  [VisitRepository] --( VisitModelAPI
}
VisitControllerAPI--[VisitController]

[User Interface] --( OwnerControllerAPI
[User Interface] --( PetControllerAPI
[User Interface] --( VisitControllerAPI

[VisitController] -[hidden]d- [OwnerManagement]

}
@enduml