@startuml
'https://plantuml.com/component-diagram
left to right direction

package "PetClinic Application" {

package "UI Layer (View)" {
     [User Interface]
}

package "PetClinic Module" {

  package "Application Logic Layer (Controller)" {
     ControllerAPI--[Controller]
     [Public API]
  }

  package "Business Logic Layer (Model)" {
     ModelAPI--[Domain Model]
     RepoAPI--[Repository]
  }

}
PublicAPI--[Public API]
[Controller] -( ExternalModulePublicAPI
}

[User Interface] --( ControllerAPI
[Controller] --( ModelAPI
[Controller] --( RepoAPI
[Public API] --( ModelAPI
[Public API] --( RepoAPI


@enduml