@startuml
'https://plantuml.com/component-diagram
top to bottom direction

package "PetClinic Module" {

  [Public API Interface]

  package "Infrastructure" {
     [Controller]
     [Repository]
     [Public API Impl]
  }

  package "Domain" {
     [Aggregates]
     [Value Objects]
  }

  [Controller] ..> [Repository]
  [Public API Impl] ..> [Repository]


}

"Infrastructure" ..> "Domain"
[Aggregates] ..> [Value Objects]
[Public API Impl] ..> [Public API Interface]
@enduml
