@startuml
'https://plantuml.com/component-diagram
left to right direction

package "PetClinic" {

  package "UI Layer (View)" {
     [User Interface]
  }

  package "Application Logic Layer (Controller)" {
     ControllerAPI--[Controller]
     PublicAPI--[Public API]
  }

  package "Business Logic Layer (Model)" {
     ModelAPI--[Domain Model]
     RepoAPI--[Repository]
  }

}

[User Interface] --( ControllerAPI
[Controller] --( ModelAPI
[Controller] --( RepoAPI
[Public API] --( ModelAPI
[Public API] --( RepoAPI


@enduml